name: Static analysis

on: [push]

jobs:
  flake8:
    name: Static analysis using flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: '**/pyproject.toml'
      - name: Install module dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bandit:
    name: Static analysis using bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: '**/pyproject.toml'
      - name:
        uses: shundor/bandit-action@v1
        with: 
            path: "."
            level: high
            confidence: high
            exit_zero: true  
  
  coverage:
    name: Static analysis using coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: '**/pyproject.toml'
      - name: Install module dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov requests
          python -m pip install .[test]
      - name: Run tests
        run: |
            pytest --junitxml=report.xml
      - name: Run coverage
        run: |
            coverage run --source=src -m pytest
            coverage report
            coverage xml
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: coverage.xml
      
      - name: Show coverage report
        uses: orgoro/coverage.xml
        with:
          path: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
